/**
 * Phala TEE Proxy API Route
 * Mocked AI processing for MVP - ready for Phat Contract integration
 */

import { NextRequest, NextResponse } from "next/server";

// Mock LLM response for demo purposes
// In production, this would be handled by the Phat Contract in TEE
async function mockLLMResponse(prompt: string): Promise<string> {
    // Simulate processing delay
    await new Promise((resolve) => setTimeout(resolve, 500));

    // Simple context-aware responses for demo
    const promptLower = prompt.toLowerCase();

    if (promptLower.includes("nda") || promptLower.includes("non-disclosure")) {
        return `# Non-Disclosure Agreement (NDA)

**Effective Date:** [DATE]

## 1. Definition of Confidential Information
"Confidential Information" means any non-public information disclosed by either party, including but not limited to:
- Business plans and strategies
- Technical data and specifications
- Customer and supplier lists
- Financial information

## 2. Obligations of Receiving Party
The Receiving Party agrees to:
- Hold Confidential Information in strict confidence
- Not disclose to third parties without prior written consent
- Use only for the purposes contemplated by this Agreement

## 3. Term
This Agreement shall remain in effect for [DURATION] from the Effective Date.

## 4. Governing Law
This Agreement shall be governed by the laws of [JURISDICTION].

---
*This document was generated by DocuMate AI Co-Pilot in a Trusted Execution Environment.*`;
    }

    if (
        promptLower.includes("contract") ||
        promptLower.includes("service agreement")
    ) {
        return `# Service Agreement

**Agreement Date:** [DATE]

## Parties
- **Service Provider:** [PROVIDER NAME]
- **Client:** [CLIENT NAME]

## Scope of Work
[DETAILED DESCRIPTION OF SERVICES]

## Compensation
- Total Amount: [AMOUNT] $DOCU
- Payment Schedule: [SCHEDULE]

## Timeline
- Start Date: [START]
- Completion Date: [END]

## Terms and Conditions
1. The Service Provider agrees to deliver work meeting industry standards.
2. The Client agrees to provide necessary resources and timely feedback.
3. Either party may terminate with [X] days written notice.

---
*Generated by DocuMate AI Co-Pilot - TEE Protected*`;
    }

    // Default response
    return `Thank you for your request. Based on your input:

"${prompt.slice(0, 100)}${prompt.length > 100 ? "..." : ""}"

I can help you draft professional documents including:
- Non-Disclosure Agreements (NDAs)
- Service Agreements
- Freelance Contracts
- Scope of Work documents

Please provide more specific details about the document you need.

---
*DocuMate AI Co-Pilot - Privacy-First Processing*`;
}

/**
 * GET - Health check endpoint
 */
export async function GET() {
    return NextResponse.json({
        status: "healthy",
        mode: "mock",
        publicKey: "0x" + "a".repeat(64),
        message: "TEE proxy running in mock mode for MVP",
    });
}

/**
 * POST - Process encrypted prompt
 */
export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { encryptedPrompt } = body;

        if (!encryptedPrompt || !encryptedPrompt.ciphertext) {
            return NextResponse.json(
                { success: false, error: "Invalid encrypted prompt" },
                { status: 400 }
            );
        }

        // Mock decryption (in production, done in TEE)
        let prompt: string;
        try {
            prompt = atob(encryptedPrompt.ciphertext);
        } catch {
            prompt = encryptedPrompt.ciphertext;
        }

        // Generate response (mock LLM call)
        const response = await mockLLMResponse(prompt);

        // Mock encryption of response
        const encryptedContent = btoa(response);

        return NextResponse.json({
            success: true,
            encryptedContent,
            // Include plain content in mock mode for debugging
            plainContent: response,
            gasUsed: Math.floor(Math.random() * 1000) + 500,
        });
    } catch (error) {
        console.error("TEE Proxy Error:", error);
        return NextResponse.json(
            {
                success: false,
                error: error instanceof Error ? error.message : "Unknown error",
            },
            { status: 500 }
        );
    }
}
