/**
 * Phala TEE Proxy API Route
 * Mocked AI processing for MVP - ready for Phat Contract integration
 */

import { NextRequest, NextResponse } from "next/server";

interface SessionContext {
    activeTemplate?: {
        id: string;
        name: string;
        description: string;
        placeholders: Array<{ key: string; label: string; type: string }>;
    } | null;
    placeholderValues?: Record<string, string>;
    didProfile?: {
        name?: string;
        role?: string;
        did?: string;
        wallet?: string | null;
    };
    recentMessages?: Array<{ role: string; content: string }>;
}

// Mock LLM response for demo purposes
// In production, this would be handled by the Phat Contract in TEE
async function mockLLMResponse(prompt: string, context?: SessionContext): Promise<string> {
    // Simulate processing delay
    await new Promise((resolve) => setTimeout(resolve, 500));

    // Simple context-aware responses for demo
    const promptLower = prompt.toLowerCase();
    const activeTemplateName = context?.activeTemplate?.name?.toLowerCase() ?? "";
    const currentFields = context?.placeholderValues ?? {};

    if (activeTemplateName.includes("non-disclosure") || activeTemplateName.includes("nda")) {
        if (promptLower.includes("purpose") || promptLower.includes("disclos") || promptLower.includes("confidential")) {
            const purpose = prompt.replace(/^with\s+a\s+purpose\s+of\s+/i, "").trim();
            return `You're still editing the active NDA session.

Suggested purpose clause:
- **Purpose**: ${purpose || "To allow limited disclosure of party identity while keeping the underlying work, methods, and confidential deliverables non-public."}

This means the agreement can be framed so the receiving party may disclose who performed the work, but may not disclose the confidential details of what was done, how it was done, or any protected materials.

If you want, I can keep applying more NDA-specific field updates in this same session.`;
        }

        return `You are still inside the active NDA drafting session for ${context?.didProfile?.name || "the current user"}.

Current known fields:
${Object.keys(currentFields).length > 0 ? Object.entries(currentFields).map(([key, value]) => `- ${key}: ${value}`).join("\n") : "- No fields captured yet"}

Continue giving NDA details naturally, for example:
- "receiver is Acme Corp"
- "purpose is evaluation of a client proposal"
- "duration is 3 years"
- "governing law is Singapore"`;
    }

    if (promptLower.includes("nda") || promptLower.includes("non-disclosure")) {
        return `# Non-Disclosure Agreement (NDA)

**Effective Date:** [DATE]

## 1. Definition of Confidential Information
"Confidential Information" means any non-public information disclosed by either party, including but not limited to:
- Business plans and strategies
- Technical data and specifications
- Customer and supplier lists
- Financial information

## 2. Obligations of Receiving Party
The Receiving Party agrees to:
- Hold Confidential Information in strict confidence
- Not disclose to third parties without prior written consent
- Use only for the purposes contemplated by this Agreement

## 3. Term
This Agreement shall remain in effect for [DURATION] from the Effective Date.

## 4. Governing Law
This Agreement shall be governed by the laws of [JURISDICTION].

---
*This document was generated by DocuMate AI Co-Pilot in a Trusted Execution Environment.*`;
    }

    if (
        promptLower.includes("contract") ||
        promptLower.includes("service agreement")
    ) {
        return `# Service Agreement

**Agreement Date:** [DATE]

## Parties
- **Service Provider:** [PROVIDER NAME]
- **Client:** [CLIENT NAME]

## Scope of Work
[DETAILED DESCRIPTION OF SERVICES]

## Compensation
- Total Amount: [AMOUNT] $DOCU
- Payment Schedule: [SCHEDULE]

## Timeline
- Start Date: [START]
- Completion Date: [END]

## Terms and Conditions
1. The Service Provider agrees to deliver work meeting industry standards.
2. The Client agrees to provide necessary resources and timely feedback.
3. Either party may terminate with [X] days written notice.

---
*Generated by DocuMate AI Co-Pilot - TEE Protected*`;
    }

    // Default response
    return `Thank you for your request. Based on your input:

"${prompt.slice(0, 100)}${prompt.length > 100 ? "..." : ""}"

I can help you draft professional documents including:
- Non-Disclosure Agreements (NDAs)
- Service Agreements
- Freelance Contracts
- Scope of Work documents

Please provide more specific details about the document you need.

---
*DocuMate AI Co-Pilot - Privacy-First Processing*`;
}

/**
 * GET - Health check endpoint
 */
export async function GET() {
    return NextResponse.json({
        status: "healthy",
        mode: "mock",
        publicKey: "0x" + "a".repeat(64),
        message: "TEE proxy running in mock mode for MVP",
    });
}

/**
 * POST - Process encrypted prompt
 */
export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { encryptedPrompt, sessionContext } = body;

        if (!encryptedPrompt || !encryptedPrompt.ciphertext) {
            return NextResponse.json(
                { success: false, error: "Invalid encrypted prompt" },
                { status: 400 }
            );
        }

        // Mock decryption (in production, done in TEE)
        let prompt: string;
        try {
            prompt = atob(encryptedPrompt.ciphertext);
        } catch {
            prompt = encryptedPrompt.ciphertext;
        }

        // Generate response (mock LLM call)
        const response = await mockLLMResponse(prompt, sessionContext);

        // Mock encryption of response
        const encryptedContent = btoa(response);

        return NextResponse.json({
            success: true,
            encryptedContent,
            // Include plain content in mock mode for debugging
            plainContent: response,
            gasUsed: Math.floor(Math.random() * 1000) + 500,
        });
    } catch (error) {
        console.error("TEE Proxy Error:", error);
        return NextResponse.json(
            {
                success: false,
                error: error instanceof Error ? error.message : "Unknown error",
            },
            { status: 500 }
        );
    }
}
